name: portfolio
description: "A portfolio."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.2 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  logger: ^2.0.2+1
  flutter_svg: ^2.0.9
  scrollview_observer: ^1.19.1
  url_launcher: ^6.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts: 
    - family : Poppins
      fonts: 
      - asset: assets/fonts/Poppins-Regular.ttf
      - asset: assets/fonts/Poppins-Thin.ttf
        weight: 300
      - asset: assets/fonts/Poppins-Light.ttf
        weight: 400
      - asset: assets/fonts/Poppins-Semibold.ttf
        weight: 500
      - asset: assets/fonts/Poppins-Bold.ttf
        weight: 600
      - asset: assets/fonts/Poppins-ExtraBold.ttf
        weight: 800
      - asset: assets/fonts/Poppins-Black.ttf
        weight: 900